spring:
  application:
    name: Spring
  datasource:
    url: jdbc:mysql://localhost:3306/seiii?characterEncoding=utf8
    username: root
#    password: password
    password: 452820
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
#    schema: classpath:schema.sql
#    data: classpath:data.sql
#    initialization-mode: always
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 8000
